"use strict";

angular.module('details.service', [])
  .factory('DeFty', ['$http','$q'
    , function($http,$q){
      return {
        getData: function(){
          var defer = $q.defer();
          $http.jsonp('http://www.qichangad.com/data/all.php?callback=JSON_CALLBACK')
            .then(function(res){
              defer.resolve(res.data.all);
            });
          return defer.promise;
        },
        getLeave: function(id){
          var defer = $q.defer();
          $http.get('/data/leave.json')
            .then(function(res){
              defer.resolve(res.data);
            },function(){
              var data =[{"id":12453,"comment":[
      {
        "username":"李逍遥",
        "contnet":"颜值高，服务好，nice",
        "time":"2017-03-12",
        "img":"images/head.png"
      },
      {
        "username":"杰哥",
        "contnet":"哎呦，不错啊",
        "time":"2017-03-18",
        "img":"images/rrr_03.jpg"
      }]},
    {
    "id":12766,
    "comment":[
      {
        "username":"李逍遥",
        "contnet":"颜值高，服务好，nice",
        "time":"2017-03-12",
        "img":"images/head.png"
      },
      {
        "username":"杰哥",
        "contnet":"哎呦，不错啊",
        "time":"2017-03-18",
        "img":"images/rrr_03.jpg"
      }
    ]},{
    "id":1276,
    "comment":[
      {
        "username":"李逍遥",
        "contnet":"颜值高，服务好，nice",
        "time":"2017-03-12",
        "img":"images/head.png"
      },
      {
        "username":"杰哥",
        "contnet":"哎呦，不错啊",
        "time":"2017-03-18",
        "img":"images/rrr_03.jpg"
      }
    ]},{
    "id":1265,
    "comment":[
      {
        "username":"李逍遥",
        "contnet":"颜值高，服务好，nice",
        "time":"2017-03-12",
        "img":"images/head.png"
      },
      {
        "username":"杰哥",
        "contnet":"哎呦，不错啊",
        "time":"2017-03-18",
        "img":"images/rrr_03.jpg"
      }
    ]},{
    "id":1234,
    "comment":[
      {
        "username":"李逍遥",
        "contnet":"颜值高，服务好，nice",
        "time":"2017-03-12",
        "img":"images/head.png"
      },
      {
        "username":"杰哥",
        "contnet":"哎呦，不错啊",
        "time":"2017-03-18",
        "img":"images/rrr_03.jpg"
      }
    ]},{
    "id":1221,
    "comment":[
      {
        "username":"李逍遥",
        "contnet":"颜值高，服务好，nice",
        "time":"2017-03-12",
        "img":"images/head.png"
      },
      {
        "username":"杰哥",
        "contnet":"哎呦，不错啊",
        "time":"2017-03-18",
        "img":"images/rrr_03.jpg"
      }
    ]},{
    "id":1211,
    "comment":[
      {
        "username":"李逍遥",
        "contnet":"颜值高，服务好，nice",
        "time":"2017-03-12",
        "img":"images/head.png"
      },
      {
        "username":"杰哥",
        "contnet":"哎呦，不错啊",
        "time":"2017-03-18",
        "img":"images/rrr_03.jpg"
      }
    ]},{
    "id":23,
    "comment":[
      {
        "username":"李逍遥",
        "contnet":"颜值高，服务好，nice",
        "time":"2017-03-12",
        "img":"images/head.png"
      },
      {
        "username":"杰哥",
        "contnet":"哎呦，不错啊",
        "time":"2017-03-18",
        "img":"images/rrr_03.jpg"
      }
    ]},{
    "id":12,
    "comment":[
      {
        "username":"李逍遥",
        "contnet":"颜值高，服务好，nice",
        "time":"2017-03-12",
        "img":"images/head.png"
      },
      {
        "username":"杰哥",
        "contnet":"哎呦，不错啊",
        "time":"2017-03-18",
        "img":"images/rrr_03.jpg"
      }
    ]},{
    "id":123,
    "comment":[
      {
        "username":"李逍遥",
        "contnet":"颜值高，服务好，nice",
        "time":"2017-03-12",
        "img":"images/head.png"
      },
      {
        "username":"杰哥",
        "contnet":"哎呦，不错啊",
        "time":"2017-03-18",
        "img":"images/rrr_03.jpg"
      }
    ]},{
    "id":231,
    "comment":[
      {
        "username":"李逍遥",
        "contnet":"颜值高，服务好，nice",
        "time":"2017-03-12",
        "img":"images/head.png"
      },
      {
        "username":"杰哥",
        "contnet":"哎呦，不错啊",
        "time":"2017-03-18",
        "img":"images/rrr_03.jpg"
      }
    ]},{
    "id":13,
    "comment":[
      {
        "username":"李逍遥",
        "contnet":"颜值高，服务好，nice",
        "time":"2017-03-12",
        "img":"images/head.png"
      },
      {
        "username":"杰哥",
        "contnet":"哎呦，不错啊",
        "time":"2017-03-18",
        "img":"images/rrr_03.jpg"
      }
    ]}];
             defer.resolve(data)
            })
          return defer.promise;
        }
      };
  }])

